import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const skills = ['Java', 'Python', 'JavaScript', 'HTML5', 'CSS', 'MySQL', 'PostgreSQL', 'MongoDB', 'Node', 'Express', 'React']

    const skillDisplay = skills.map((skill, i) =>{
        return (
            <div className='skill' key={i}>
                        <div>
                            <Image 
                                src={`/${skill}.png`}
                                alt={`${skill} logo`}
                                width = {55}
                                height = {50}
                                className='image'
                            />
                        </div>
                        <div>
                            <h4>{skill}</h4>
                        </div>
            </div>
        )
    })
  return (
    <div className='about'>
      <Head>
        <title>{`Sean F`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{`Welcome to Sean's Website`}</h1>
      <div className='profile'>
          <div className='screenshot'>
          <Image 
          src='/Profile2.png'
          alt='logo'
          width={300}
          height={300}
          className='profile-pic'
          />
          </div>

          <div className='description'>
              <p>My name is Sean and I am an aspiring software engineer with a background in biomaterial research. I currently live in the San Francisco Bay Area.</p>
              <p>I like learning new things, meeting new people, and coming up with new ideas.</p>
              <br></br>
              <br></br>
              <div className='icons'>
                  <div className='resume'>
                      <a href='https://drive.google.com/file/d/1HOGOBOsBPhMZqSC5M2Hl-YjL4FVf2ZiH/view?usp=share_link'> 
                          <Image 
                              src='/Resume2.png'
                              alt='resume'
                              width={50}
                              height={50}
                          />
                      </a>
                  </div>
                  
                  <div className='github'>
                      <a href='https://github.com/mousesaver'>
                              <Image 
                                  src='/icon.png'
                                  alt='github'
                                  width={50}
                                  height={50}
                              />
                      </a>
                  </div>
                  <div className='linkedin'>
                      <a href='https://www.linkedin.com/in/sean-f45/'> 
                          <Image 
                              src='/LinkedIn.png'
                              alt='github'
                              width={50}
                              height={50}
                          />
                      </a>
                  </div>
              </div>
          </div>
      </div>
      <br></br>
      <br></br>
      <br></br>

      <div className='skills-container'>
          <h2>Skills</h2>
          <div className='skills'>
              {skillDisplay}
              
          </div>
          
      </div>
      
      {/* load an image locally */}
    
  </div>

  )
}
